version: "3.8"
services:
    reel-journal-pg:
        image: postgres:13.5
        restart: always
        environment:
            - POSTGRES_USER=reel-journal-pg
            - POSTGRES_PASSWORD=reeljournalpg
        volumes:
            - postgres:/var/lib/postgresql/data
        ports:
            - "15434:5432"

volumes:
    postgres:
